<?php

/*
 * @file
 * "Leaflet MapBox" adds integration for Leaflet module with MapBox tiles.
 */

/**
 * Implements hook_menu().
 */
function leaflet_mapbox_menu() {
  $items = array();
  $items['admin/config/services/leaflet-mapbox'] = array(
    'title' => 'Leaflet MapBox configuration',
    'description' => 'Leaflet MapBox configuration panel.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('leaflet_mapbox_configuration_form'),
    'access arguments' => array('administer site'),
    'file' => 'leaflet_mapbox.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_leaflet_map_info().
 */
function leaflet_mapbox_leaflet_map_info() {
  $map_info = array();
  $map_configs = variable_get('leaflet_mapbox_configs', array());
  foreach ($map_configs as $id => $map_config) {
    $settings = array(
      'attributionControl' => TRUE,
      'closePopupOnClick'  => TRUE,
      'doubleClickZoom'    => TRUE,
      'dragging'           => TRUE,
      'fadeAnimation'      => TRUE,
      'layerControl'       => FALSE,
      'maxZoom'            => 18,
      'minZoom'            =>  0,
      'scrollWheelZoom'    => TRUE,
      'touchZoom'          => TRUE,
      'trackResize'        => TRUE,
      'zoom'               => $map_config['zoomlevel'],
      'zoomAnimation'      => TRUE,
      'zoomControl'        => TRUE,
    );
    $code = $map_config['mapbox_code'];
    $map_info["leaflet-mapbox-$id"] = array(
      'label' => $map_config['label'],
      'description' => $map_config['description'],
      'settings' => $settings,
      'layers' => array(
        'earth' => array(
          // Use headless protocol so it works for both HTTP and HTTPS
          'urlTemplate' => "//{s}.tiles.mapbox.com/v3/$code/{z}/{x}/{y}.png",
          'options' => array('attribution' => ''),
        )
      )
    );
  }
  return $map_info;
}
